### ISSUE TITLE
Cannot compile develop without gmsh

### ISSUE THREAD

**Issue by ishovkun** [ishovkun/msh2gprs#3]
Need to disable certain portions of code if gmsh is not linked.

**Comment by ishovkun** [comment]
@jaewooan I am on it.

**Comment by ishovkun** [comment]
@jaewooan let me know if you can compile now

**Comment by jaewooan** [comment]
@ishovkun I will check this after the class this morning!

**Comment by jaewooan** [comment]
It works. Thank you :)

**Comment by ishovkun** [comment]
Apparently, it works, so I'm closing this.
